# These settings are synced to GitHub by https://probot.github.io/apps/settings/

labels:
  - name: bug
    color: d73a4a
    description: An error, ambiguity, or inconsistency in the annotation guideline

  - name: task
    color: 0e8a16
    description: A general task related to maintaining or updating the guideline

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: invalid
    color: e4e669
    description: This doesn't seem right

  - name: question
    color: d876e3
    description: Further information is requested
